site_name: "LETO MVP"
site_url: https://apiad.net
repo_url: https://github.com/LETO-ai/leto-mvp
edit_uri: ""

remote_branch: master

theme:
  name: material
  # favicon: avatar.png
  # logo: avatar.png
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: UA-35980410-3
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LETO-ai
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/AlejandroPiad
    # - icon: fontawesome/brands/linkedin
    #   link: https://linkedin.com/in/apiad
    # - icon: fontawesome/brands/reddit
    #   link: https://reddit.com/u/apiad
    # - icon: fontawesome/brands/telegram
    #   link: https://t.me/mostly_harmless_ai

copyright: "&copy; 2021 - University of Alicante & University of Havana"

markdown_extensions:
  - codehilite
  - toc:
      permalink: True
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 🏠 Home: index.md
  - 📝 User Guide: guide.md
  - 🛠️ Development Guide: dev.md
