version: "3"

services:
  leto:
    image: letoai/leto:latest
    container_name: leto
    user: "1000"
    build: .
    ports:
      - 8501:8501
    volumes:
      - ../leto:/usr/local/lib/python3.8/site-packages/leto
      - ../:/home/coder/leto
      - vscode-leto-extensions:/home/coder/.vscode-server/extensions
    working_dir: "/home/coder/leto"
    command: ["streamlit", "run", "leto.py"]

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/12345678

volumes:
  vscode-leto-extensions:
