version: "3"

services:
  leto:
    image: letoai/leto:latest
    container_name: leto
    user: "1000"
    build: .
    ports:
      - 8501:8501
    volumes:
      - ../leto:/usr/local/lib/python3.8/site-packages/leto
      - ../:/home/coder/leto
      - ../data/opennre/:/home/coder/.opennre
      - vscode-leto:/home/coder/.vscode-server
    working_dir: "/home/coder/leto"
    command: ["streamlit", "run", "leto.py"]
    depends_on:
      - neo4j

  docs:
    image: letoai/docs:latest
    container_name: leto-docs
    build:
      dockerfile: docs.dockerfile
      context: .
    ports:
      - 8000:8000
    volumes:
      - ..:/home/coder/leto
    working_dir: "/home/coder/leto"
    command: ["mkdocs", "serve", "-a", "0.0.0.0:8000"]

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
    volumes:
      - "../data/neo4j:/var/lib/neo4j/data"
    environment:
      - NEO4J_AUTH=neo4j/12345678

volumes:
  vscode-leto:
